// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace BitcoinForecast
{
    class Program
    {
        static void Main(string[] args)
        {
            // predict with default option.
            var modelOutput = BitcoinForecastingModel.Predict();


            Console.Write("Nhap so gio de du doan: ");

            int horizion = int.Parse(Console.ReadLine() ?? "5");

            // predict next 5 periods
            modelOutput = BitcoinForecastingModel.Predict(horizon: horizion);
            Console.WriteLine(string.Join("\n", modelOutput.CLOSE));

            // update and predict model
            // TBD
        }
    }
}

